AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating VPC, internet gateway , gatewayattachment

Parameters:
  VPCId:
    Description: Name of VPC Id Output
    Type: String
    Default: demoVPC1ID
  GatewayId:
    Description: Name of Gateway Id Output
    Type: String
    Default: demoGatewayID


Resources:
 # VPC
  demoVPC1:
    Type: AWS::EC2::VPC
    
    Properties:
      CidrBlock: 10.0.0.0/16     #half of ip range
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Project
         Value: atudevopsdemo1vpc

# Internet GatewaY  - for internet via Gateway
  demoGateway1:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: demoGateway1  

# Associate Gateway & VPC   - connect demovpc1 and demogateway1
  demoGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref demoVPC1
      InternetGatewayId: !Ref demoGateway1


Outputs:
  demoVPC1:
    Description: Top level VPC Id
    Value:
      Ref: demoVPC1
    Export:
      Name: !Ref VPCId
      #json - initiate , yaml import
      
  demoGateway1:
    Description: Internet Gateway Id
    Value:
      Ref: demoGateway1
    Export:
      Name: !Ref GatewayId
